
platform :ios, '9.0'

target 'FuncExample' do
	use_frameworks!
	
	pod 'Func', :path => '../'
#	pod 'Func/Views', :path => '../'
#	pod 'Func/Geocoding', :path => '../'
#	pod 'Func/API', :path => '../'
#	pod 'Func/JSON', :path => '../'

	pod 'AlamofireImage', '~> 3.3'
	
end
